semikolan-co/semikolan-react

README.md
Fixes #35 
Added  about ```About SemiKolan``` in ```README.md```. 
Added link to Discord.
=> Readme add about

src/component/Footer.js, src/component/Work.js, src/semikolan.json
This PR fixes the name issues associated to semikolan-dev to semikolan-co
Fixes #39
=> Fix name issues in src files

src/App.js, src/component/Community.js, src/component/Contact.js, src/json/semikolan.json, src/pages/Home.js
=> second commit

src/App.js, src/component/MovingCursor.css, src/component/MovingCursor.js
=> Added Moving Cursor

package.json, src/App.js, src/component/MovingCursor.css, src/component/MovingCursor.js
=> Removed Unneccesary stuffs from package.json and Fixed small bugs

src/pages/Home/index.js
=> Commented Works section

package-lock.json, package.json
=> Fixed React Lottie Missing Issue

.env.example, .gitignore, package-lock.json, package.json, src/component/ContactForm.js
=> Added Supabase in Contact form

src/component/ContactForm.js, src/component/Footer.js, src/supabase.js
=> connected Newsletter Request with Supabase

src/json/communities.json, src/json/communities.jsonc, src/pages/Events/style.scss
=> Made Events Page Responsive and Added Script Foundation in communities 

package-lock.json, src/pages/Hacktober.js
Hacktoberfest has officially started but the [website](https://semikolan.co/hacktoberfest) still says "Registration will be open soon!"
=> update hacktoberfest link

src/assets/css/Hacktober.css, src/pages/Hacktober.js
Reverts semikolan-co/semikolan-react#123
=> Revert "ui-improved"

src/assets/css/Hacktober.css, src/pages/Hacktober.js
Reverts semikolan-co/semikolan-react#125
=> Revert "ui-done"

src/App.js, src/assets/css/Hacktober.css, src/pages/Hacktober.js
=> hacktober final changes

src/pages/Hacktober.js
=> Read-me update

src/assets/css/hacktober.css, src/pages/Hacktober.js
Timeline section is the most important in hacktoberfest page.
Moved the Timeline section to up of project repository section in /hactoberfest page as we need to scroll to bottom for seeing timeline.
Fixes #139 
- Moved the section in hacktoberfest.js
- Add top padding for timeline section
- removed top padding to project section
-
=> Timeline section fix

src/App.js, src/assets/css/hacktober.css, src/json/leaderboard.json, src/pages/Hacktober.js
=> added leaderboard UI

src/App.js, src/assets/css/hacktober.css, src/pages/Hacktober.js, src/pages/hacktoberboard.js
=> added leaderboard of hacktoberfest

src/component/Header.js
Add navigation to Hacktoberfest Page from Homepage
- New feature (non-breaking change which adds functionality)
- My code follows the style guidelines of this project
-  I have performed a self-review of my own code
-  My changes generate no new warnings
-  I have checked my code and corrected any misspellings
=> [add] Link from Home to Hacktoberfest Page

src/assets/css/hacktober.css
=> Responsive leaderboard

src/pages/Hacktober.js
=> Added leaderboard section in hacktoberfest

src/component/Projects.js, src/pages/HacktoberBoard.js, src/utils/index.js
=> Search Functionality on Leaderboard in hacktoberfest page

src/assets/css/layout.css, src/component/LeaderBoardPagination.js, src/component/Pagination.css, src/pages/HacktoberBoard.js
1. Created pagination functionality in the leaderboard.
2. Added styling to the pagination component.
https://user-images.githubusercontent.com/47183818/197318284-3c56d37c-9bc4-455b-a0b0-cfa24e443d48.mov
**Note(s)**
* There are existing unused variables and imports in HacktoberBoard and LeaderBoardPagination that can be removed.
* leader_board_pagination class is commented out as it was not doing anything. This can be removed upon request. 
Fixes # 171
=> Created Pagination Functionality & Improved Styling of Pagination Component
